name: 'HCL OneTest Server'
description: 'Execute OTS Test from GitHub Action'
inputs:
  serverUrl:
    description: 'HCL OneTest Server URL'
    required: true
  offlineToken:
    description: 'HCL OneTest Server OfflineToken'
    required: true
  teamspace:
    description: 'Team Space name of the project.'
    required: true
  project:
    description: 'Project name of the test.'
    required: true
  branch:
    description: 'Branch name corresponding to the test.'
    required: true
  assetId:
    description: 'AssetId of the test in HCL OneTest Server.'
    required: true
  environment:
    description: 'Optional. Test environment corresponding to the test. Mandatory to input the value if you want to run API test.'  
    required: false
  datasets:
    description: 'Optional. Comma (,) delimited values of datasets for the job to run, For example: source:replacement;source:replacement'
    required: false
  variables:
    description: 'Optional. Variables corresponding to the test. You must enter the variables in the format: name_of_the_variable=value_of_the_variable'
    required: false
  tags:
    description: 'Optional. Tags corresponding to the test. For example: label1, label2'
    required: false      
runs:
  using: 'node16'
  main: 'dist/index.js' 
