name: HCL OneTest Server

on:
    workflow_dispatch:
        inputs:
            serverUrl:
                description: 'Server URL'
                required: true
            offlineToken:
                description: 'Offline Token'
                required: true
            teamspace:
                description: 'Team Space Name'
                required: true
            project:
                description: 'Project'
                required: true
            branch:
                description: 'Branch'
                required: true
            assetId:
                description: 'AssetID'
                required: true
            environment:
                description: 'API Test Environment'
                required: false
            datasets:
                description: 'Datasets'
                required: false
            exportReport:
                description: 'Export Junit Report'
                required: false
            multipleValues:
                description: 'Multiple Values'
                required: false

jobs:

    OTS-Action:
        runs-on: self-hosted
        name: HCL OneTest Server
        steps:
         - name: Execute Test
           uses: SonaHJ/OTSAction@main
           with:
            serverUrl: '${{ github.event.inputs.serverUrl }}'
            offlineToken: '${{ github.event.inputs.offlineToken }}'
            teamspace: '${{ github.event.inputs.teamspace }}'
            project: '${{ github.event.inputs.project }}'
            branch: '${{ github.event.inputs.branch }}'
            assetId: '${{ github.event.inputs.assetId }}'
            environment: '${{ github.event.inputs.environment }}'
            datasets: '${{ github.event.inputs.datasets }}'
            exportReport: '${{ github.event.inputs.exportReport }}'
            multipleValues: '${{ github.event.inputs.multipleValues }}'
